{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# This script is to facillitate the upload of fine tuning data for bayes beats"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting google-cloud-core\n",
      "  Downloading google_cloud_core-2.4.3-py2.py3-none-any.whl (29 kB)\n",
      "Collecting google-auth\n",
      "  Downloading google_auth-2.40.2-py2.py3-none-any.whl (216 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m216.1/216.1 kB\u001b[0m \u001b[31m2.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hCollecting google-auth-oauthlib\n",
      "  Downloading google_auth_oauthlib-1.2.2-py3-none-any.whl (19 kB)\n",
      "Collecting gcsfs\n",
      "  Downloading gcsfs-2025.5.0.post1-py2.py3-none-any.whl (36 kB)\n",
      "Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.6\n",
      "  Downloading google_api_core-2.24.2-py3-none-any.whl (160 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m160.1/160.1 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting pyasn1-modules>=0.2.1\n",
      "  Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)\n",
      "Collecting rsa<5,>=3.1.4\n",
      "  Downloading rsa-4.9.1-py3-none-any.whl (34 kB)\n",
      "Collecting cachetools<6.0,>=2.0.0\n",
      "  Using cached cachetools-5.5.2-py3-none-any.whl (10 kB)\n",
      "Collecting requests-oauthlib>=0.7.0\n",
      "  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)\n",
      "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from gcsfs) (3.11.18)\n",
      "Requirement already satisfied: requests in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from gcsfs) (2.32.3)\n",
      "Collecting google-cloud-storage\n",
      "  Downloading google_cloud_storage-3.1.0-py2.py3-none-any.whl (174 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m174.9/174.9 kB\u001b[0m \u001b[31m7.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting fsspec==2025.5.0\n",
      "  Using cached fsspec-2025.5.0-py3-none-any.whl (196 kB)\n",
      "Requirement already satisfied: decorator>4.1.2 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from gcsfs) (5.2.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.20.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (6.4.4)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (2.6.1)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.6.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.3.2)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (0.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (25.3.0)\n",
      "Requirement already satisfied: async-timeout<6.0,>=4.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (5.0.1)\n",
      "Collecting proto-plus<2.0.0,>=1.22.3\n",
      "  Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m50.2/50.2 kB\u001b[0m \u001b[31m1.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting googleapis-common-protos<2.0.0,>=1.56.2\n",
      "  Downloading googleapis_common_protos-1.70.0-py3-none-any.whl (294 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m294.5/294.5 kB\u001b[0m \u001b[31m1.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.6->google-cloud-core) (6.31.0)\n",
      "Collecting pyasn1<0.7.0,>=0.6.1\n",
      "  Using cached pyasn1-0.6.1-py3-none-any.whl (83 kB)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->gcsfs) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->gcsfs) (2.4.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->gcsfs) (2025.4.26)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->gcsfs) (3.4.2)\n",
      "Collecting oauthlib>=3.0.0\n",
      "  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)\n",
      "Collecting google-crc32c<2.0dev,>=1.0\n",
      "  Downloading google_crc32c-1.7.1-cp310-cp310-macosx_12_0_x86_64.whl (30 kB)\n",
      "Collecting google-resumable-media>=2.7.2\n",
      "  Using cached google_resumable_media-2.7.2-py2.py3-none-any.whl (81 kB)\n",
      "Requirement already satisfied: typing-extensions>=4.1.0 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (4.13.2)\n",
      "Installing collected packages: pyasn1, proto-plus, oauthlib, googleapis-common-protos, google-crc32c, fsspec, cachetools, rsa, requests-oauthlib, pyasn1-modules, google-resumable-media, google-auth, google-auth-oauthlib, google-api-core, google-cloud-core, google-cloud-storage, gcsfs\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 2024.12.0\n",
      "    Uninstalling fsspec-2024.12.0:\n",
      "      Successfully uninstalled fsspec-2024.12.0\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "datasets 3.4.1 requires fsspec[http]<=2024.12.0,>=2023.1.0, but you have fsspec 2025.5.0 which is incompatible.\n",
      "ace-step 0.2.0 requires diffusers>=0.33.0, but you have diffusers 0.27.2 which is incompatible.\n",
      "ace-step 0.2.0 requires transformers==4.50.0, but you have transformers 4.37.2 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed cachetools-5.5.2 fsspec-2025.5.0 gcsfs-2025.5.0.post1 google-api-core-2.24.2 google-auth-2.40.2 google-auth-oauthlib-1.2.2 google-cloud-core-2.4.3 google-cloud-storage-3.1.0 google-crc32c-1.7.1 google-resumable-media-2.7.2 googleapis-common-protos-1.70.0 oauthlib-3.2.2 proto-plus-1.26.1 pyasn1-0.6.1 pyasn1-modules-0.4.2 requests-oauthlib-2.0.0 rsa-4.9.1\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install google-cloud-core google-auth google-auth-oauthlib gcsfs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datasets import load_dataset\n",
    "from google.cloud import storage\n",
    "import os\n",
    "from tqdm import tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Your browser has been opened to visit:\n",
      "\n",
      "    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=60z9OYq3w3ss5HXp29BxvrendQbH4u&access_type=offline&code_challenge=pFw1San5YFEIjczOk5pLn-q3rKCqhliQ2SIhlVHyVoc&code_challenge_method=S256\n",
      "\n",
      "\n",
      "Credentials saved to file: [/Users/kwaku/.config/gcloud/application_default_credentials.json]\n",
      "\n",
      "These credentials will be used by any library that requests Application Default Credentials (ADC).\n",
      "\u001b[1;33mWARNING:\u001b[0m \n",
      "Cannot add the project \"pk-arg-prj4-datasci\" to ADC as the quota project because the account in ADC does not have the \"serviceusage.services.use\" permission on this project. You might receive a \"quota_exceeded\" or \"API not enabled\" error. Run $ gcloud auth application-default set-quota-project to add a quota project.\n",
      "\n",
      "\n",
      "Updates are available for some Google Cloud CLI components.  To install them,\n",
      "please run:\n",
      "  $ gcloud components update\n",
      "\n",
      "\n",
      "\n",
      "To take a quick anonymous survey, run:\n",
      "  $ gcloud survey\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!gcloud auth application-default login\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n",
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n",
      "Downloading data:   1%|          | 12/1030 [05:29<7:45:51, 27.46s/files]\n"
     ]
    }
   ],
   "source": [
    "from datasets import load_dataset\n",
    "from google.cloud import storage\n",
    "import soundfile as sf\n",
    "import io\n",
    "import json\n",
    "from tqdm import tqdm\n",
    "\n",
    "# Config\n",
    "BATCH_SIZE = 100\n",
    "MAX_RECORDS = 1000\n",
    "SPLIT = \"train\"\n",
    "BUCKET_NAME = \"uchicago-bayesian-bayes-beats\"\n",
    "\n",
    "# GCS\n",
    "client = storage.Client()\n",
    "bucket = client.bucket(BUCKET_NAME)\n",
    "\n",
    "# Load dataset\n",
    "dataset = load_dataset(\"vikhyatk/lofi\", split=SPLIT)\n",
    "\n",
    "# Batch over the dataset\n",
    "for start in range(0, min(len(dataset), MAX_RECORDS), BATCH_SIZE):\n",
    "    end = min(start + BATCH_SIZE, len(dataset))\n",
    "    batch = dataset.select(range(start, end))\n",
    "\n",
    "    for i, record in enumerate(tqdm(batch, desc=f\"Uploading records {start}–{end}\")):\n",
    "        try:\n",
    "            audio = record[\"audio\"]\n",
    "            audio_array = audio[\"array\"]\n",
    "            sample_rate = audio[\"sampling_rate\"]\n",
    "\n",
    "            # Trim to 30 seconds\n",
    "            max_samples = 30 * sample_rate\n",
    "            trimmed = audio_array[:max_samples]\n",
    "\n",
    "            # Write WAV to memory\n",
    "            buffer = io.BytesIO()\n",
    "            sf.write(buffer, trimmed, sample_rate, format=\"WAV\")\n",
    "            buffer.seek(0)\n",
    "\n",
    "            # Generate synthetic file name\n",
    "            base_name = f\"{start + i:06d}\"\n",
    "            blob = bucket.blob(f\"vikhyatk/lofi/{base_name}.wav\")\n",
    "            blob.upload_from_file(buffer, content_type=\"audio/wav\")\n",
    "\n",
    "            # Upload metadata JSON\n",
    "            metadata = {k: v for k, v in record.items() if k != \"audio\"}\n",
    "            meta_blob = bucket.blob(f\"vikhyatk/lofi/{base_name}.json\")\n",
    "            meta_blob.upload_from_string(json.dumps(metadata), content_type=\"application/json\")\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"❌ Failed on record {start + i}: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## parallel execution"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n",
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "❌ MTG-Jamendo_dataset.zip is not a valid ZIP. Please download using wget as instructed.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[26], line 25\u001b[0m\n\u001b[1;32m     23\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mzipfile\u001b[39;00m\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m zipfile\u001b[38;5;241m.\u001b[39mis_zipfile(LOCAL_ZIP):\n\u001b[0;32m---> 25\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m❌ MTG-Jamendo_dataset.zip is not a valid ZIP. Please download using wget as instructed.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     27\u001b[0m \u001b[38;5;66;03m# --- EXTRACT ZIP ---\u001b[39;00m\n\u001b[1;32m     28\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m EXTRACT_DIR\u001b[38;5;241m.\u001b[39mexists():\n",
      "\u001b[0;31mValueError\u001b[0m: ❌ MTG-Jamendo_dataset.zip is not a valid ZIP. Please download using wget as instructed."
     ]
    }
   ],
   "source": [
    "import os\n",
    "import zipfile\n",
    "import requests\n",
    "import io\n",
    "import json\n",
    "from pathlib import Path\n",
    "from tqdm import tqdm\n",
    "from pydub import AudioSegment\n",
    "from google.cloud import storage\n",
    "\n",
    "# --- CONFIG ---\n",
    "BUCKET_NAME = \"uchicago-bayesian-bayes-beats\"\n",
    "MAX_FILES = 1000\n",
    "LOCAL_ZIP = \"/Users/kwaku/Development/research/bayes_beats/MTG-Jamendo_dataset.zip\"\n",
    "EXTRACT_DIR = Path(\"jamendo_dataset\")\n",
    "AUDIO_BASE_URL = \"https://datasets.i-know-this-song.com/audio/{}.mp3\"\n",
    "\n",
    "# --- SETUP GCS ---\n",
    "client = storage.Client()\n",
    "bucket = client.bucket(BUCKET_NAME)\n",
    "\n",
    "# --- VERIFY ZIP ---\n",
    "import zipfile\n",
    "if not zipfile.is_zipfile(LOCAL_ZIP):\n",
    "    raise ValueError(\"❌ MTG-Jamendo_dataset.zip is not a valid ZIP. Please download using wget as instructed.\")\n",
    "\n",
    "# --- EXTRACT ZIP ---\n",
    "if not EXTRACT_DIR.exists():\n",
    "    print(\"📦 Extracting ZIP...\")\n",
    "    with zipfile.ZipFile(LOCAL_ZIP, 'r') as zip_ref:\n",
    "        zip_ref.extractall(EXTRACT_DIR)\n",
    "    print(\"✅ Extracted to:\", EXTRACT_DIR)\n",
    "\n",
    "# --- PARSE TRACK IDS FROM split-0.json ---\n",
    "split_file = EXTRACT_DIR / \"MTG-Jamendo_dataset\" / \"split-0.json\"\n",
    "if not split_file.exists():\n",
    "    raise FileNotFoundError(\"❌ split-0.json not found in extracted metadata.\")\n",
    "\n",
    "with open(split_file) as f:\n",
    "    split_data = json.load(f)\n",
    "\n",
    "track_ids = [t[\"id\"] for t in split_data[\"tracks\"][:MAX_FILES]]\n",
    "track_map = {t[\"id\"]: t for t in split_data[\"tracks\"]}\n",
    "\n",
    "print(f\"🎵 Preparing to upload {len(track_ids)} tracks to GCS...\")\n",
    "\n",
    "# --- PROCESS AND UPLOAD AUDIO ---\n",
    "for track_id in tqdm(track_ids, desc=\"Uploading tracks\"):\n",
    "    try:\n",
    "        # Download MP3\n",
    "        url = AUDIO_BASE_URL.format(track_id)\n",
    "        response = requests.get(url)\n",
    "        response.raise_for_status()\n",
    "\n",
    "        # Load .mp3 into pydub and trim to 30s\n",
    "        audio = AudioSegment.from_file(io.BytesIO(response.content), format=\"mp3\")\n",
    "        audio = audio[:30_000]\n",
    "\n",
    "        # Export to in-memory .wav buffer\n",
    "        buffer = io.BytesIO()\n",
    "        audio.export(buffer, format=\"wav\")\n",
    "        buffer.seek(0)\n",
    "\n",
    "        # Upload audio\n",
    "        audio_blob = bucket.blob(f\"mtg-jamendo/{track_id}.wav\")\n",
    "        audio_blob.upload_from_file(buffer, content_type=\"audio/wav\")\n",
    "\n",
    "        # Upload metadata\n",
    "        metadata = track_map[track_id]\n",
    "        meta_blob = bucket.blob(f\"mtg-jamendo/{track_id}.json\")\n",
    "        meta_blob.upload_from_string(json.dumps(metadata), content_type=\"application/json\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Failed on track {track_id}: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting zenodo-get\n",
      "  Downloading zenodo_get-2.0.0-py3-none-any.whl (34 kB)\n",
      "Requirement already satisfied: click in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from zenodo-get) (8.1.8)\n",
      "Collecting coverage>=7.8.2\n",
      "  Downloading coverage-7.8.2-cp310-cp310-macosx_10_9_x86_64.whl (211 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m211.6/211.6 kB\u001b[0m \u001b[31m3.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: requests in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from zenodo-get) (2.32.3)\n",
      "Collecting humanize\n",
      "  Downloading humanize-4.12.3-py3-none-any.whl (128 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m128.5/128.5 kB\u001b[0m \u001b[31m8.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting wget\n",
      "  Downloading wget-3.2.zip (10 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: certifi>=2017.4.17 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->zenodo-get) (2025.4.26)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->zenodo-get) (3.4.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->zenodo-get) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages (from requests->zenodo-get) (2.4.0)\n",
      "Installing collected packages: wget, humanize, coverage, zenodo-get\n",
      "\u001b[33m  DEPRECATION: wget is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559\u001b[0m\u001b[33m\n",
      "\u001b[0m  Running setup.py install for wget ... \u001b[?25ldone\n",
      "\u001b[?25hSuccessfully installed coverage-7.8.2 humanize-4.12.3 wget-3.2 zenodo-get-2.0.0\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n",
      "Title: Data from: Kin effects on energy allocation in group-living ground squirrels\n",
      "Keywords: reproductive allocation, matriline, somatic allocation, Philopatry, 1992-2014, Urocitellus columbianus, energy\n",
      "Publication date: 2017-04-25\n",
      "DOI: 10.5061/dryad.50hk0\n",
      "Total size: 10.3 kB\n",
      "\n",
      "Downloading (1/1):\n",
      "File: Viblanc et al. 2016_JAE.csv (10.3 kB)\n",
      "Link: https://zenodo.org/api/records/4984208/files/Viblanc et al. 2016_JAE.csv/content\n",
      "100% [..........................................................] 10345 / 10345\n",
      "Checksum is correct for Viblanc et al. 2016_JAE.csv. (6f0e5a09c4e513748ab2943aa718ed0b)\n",
      "\n",
      "All specified files have been processed.\n"
     ]
    }
   ],
   "source": [
    "!pip install zenodo-get\n",
    "!zenodo_get 4984208\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n",
      "                                 Dload  Upload   Total   Spent    Left  Speed\n",
      "100   279  100   279    0     0    274      0  0:00:01  0:00:01 --:--:--   274\n",
      "100 14305  100 14305    0     0   8694      0  0:00:01  0:00:01 --:--:--     0\n"
     ]
    }
   ],
   "source": [
    "!curl -L \"https://zenodo.org/record/4984208/files/MTG-Jamendo_dataset.zip?download=1\" -o MTG-Jamendo_dataset.zip\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting numpy<2\n",
      "  Downloading numpy-1.26.4-cp310-cp310-macosx_10_9_x86_64.whl (20.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m20.6/20.6 MB\u001b[0m \u001b[31m7.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0mm\n",
      "\u001b[?25hInstalling collected packages: numpy\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 2.2.6\n",
      "    Uninstalling numpy-2.2.6:\n",
      "      Successfully uninstalled numpy-2.2.6\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "torchvision 0.17.2 requires torch==2.2.2, but you have torch 2.1.2 which is incompatible.\n",
      "thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.\n",
      "py3langid 0.3.0 requires numpy>=2.0.0; python_version >= \"3.9\", but you have numpy 1.26.4 which is incompatible.\n",
      "datasets 3.4.1 requires fsspec[http]<=2024.12.0,>=2023.1.0, but you have fsspec 2025.5.0 which is incompatible.\n",
      "ace-step 0.2.0 requires diffusers>=0.33.0, but you have diffusers 0.27.2 which is incompatible.\n",
      "ace-step 0.2.0 requires transformers==4.50.0, but you have transformers 4.37.2 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed numpy-1.26.4\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install \"numpy<2\" --force-reinstall"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n",
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🎵 Fetching up to 20 'rock' tracks from Jamendo...\n",
      "✅ Retrieved 20 tracks\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Uploading to GCS: 100%|██████████| 20/20 [03:46<00:00, 11.33s/it]\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "import io\n",
    "from pathlib import Path\n",
    "from google.cloud import storage\n",
    "from tqdm import tqdm\n",
    "\n",
    "# --- CONFIG ---\n",
    "BUCKET_NAME = \"uchicago-bayesian-bayes-beats\"\n",
    "GCS_FOLDER = \"jamendo\"\n",
    "TAG = \"rock\"\n",
    "MAX_TRACKS = 20\n",
    "CLIENT_ID = \"a62fe3ee\"  # Jamendo test client_id\n",
    "AUDIO_FORMAT = \"mp32\"   # 320kbps\n",
    "\n",
    "# --- SETUP GCS ---\n",
    "client = storage.Client()\n",
    "bucket = client.bucket(BUCKET_NAME)\n",
    "\n",
    "# --- FETCH TRACKS ---\n",
    "print(f\"🎵 Fetching up to {MAX_TRACKS} '{TAG}' tracks from Jamendo...\")\n",
    "response = requests.get(\n",
    "    \"https://api.jamendo.com/v3.0/tracks\",\n",
    "    params={\n",
    "        \"client_id\": CLIENT_ID,\n",
    "        \"format\": \"json\",\n",
    "        \"limit\": MAX_TRACKS,\n",
    "        \"audioformat\": AUDIO_FORMAT,\n",
    "        \"include\": \"musicinfo\",\n",
    "        \"tags\": TAG\n",
    "    }\n",
    ")\n",
    "tracks = response.json()[\"results\"]\n",
    "print(f\"✅ Retrieved {len(tracks)} tracks\")\n",
    "\n",
    "# --- PROCESS TRACKS ---\n",
    "for i, track in enumerate(tqdm(tracks, desc=\"Uploading to GCS\")):\n",
    "    try:\n",
    "        title = track[\"name\"].replace(\" \", \"_\")\n",
    "        artist = track[\"artist_name\"].replace(\" \", \"_\")\n",
    "        filename = f\"{i:03d}_{artist}_{title}.mp3\"\n",
    "\n",
    "        # Download MP3 to memory\n",
    "        audio_resp = requests.get(track[\"audio\"])\n",
    "        audio_resp.raise_for_status()\n",
    "        buffer = io.BytesIO(audio_resp.content)\n",
    "\n",
    "        # Upload MP3 to GCS\n",
    "        audio_blob = bucket.blob(f\"{GCS_FOLDER}/{filename}\")\n",
    "        audio_blob.upload_from_file(buffer, content_type=\"audio/mpeg\")\n",
    "\n",
    "        # Upload metadata as JSON\n",
    "        metadata = {\n",
    "            \"id\": track[\"id\"],\n",
    "            \"name\": track[\"name\"],\n",
    "            \"artist\": track[\"artist_name\"],\n",
    "            \"album\": track.get(\"album_name\"),\n",
    "            \"duration\": track[\"duration\"],\n",
    "            \"tags\": track.get(\"musicinfo\", {}).get(\"tags\", []),\n",
    "            \"genres\": track.get(\"musicinfo\", {}).get(\"genres\", []),\n",
    "            \"instruments\": track.get(\"musicinfo\", {}).get(\"instruments\", []),\n",
    "            \"vocalinstrumental\": track.get(\"musicinfo\", {}).get(\"vocalinstrumental\", None),\n",
    "        }\n",
    "        meta_blob = bucket.blob(f\"{GCS_FOLDER}/{filename.replace('.mp3', '.json')}\")\n",
    "        meta_blob.upload_from_string(json.dumps(metadata), content_type=\"application/json\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Failed on {track['name']}: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n",
      "/Users/kwaku/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🎧 Processing genre: electronic\n",
      "→ Retrieved 20 tracks for electronic\n",
      "\n",
      "🎧 Processing genre: jazz\n",
      "→ Retrieved 20 tracks for jazz\n",
      "\n",
      "🎧 Processing genre: hiphop\n",
      "→ Retrieved 20 tracks for hiphop\n",
      "\n",
      "🎧 Processing genre: classical\n",
      "→ Retrieved 20 tracks for classical\n",
      "\n",
      "🎧 Processing genre: metal\n",
      "→ Retrieved 20 tracks for metal\n",
      "\n",
      "🎧 Processing genre: soundtrack\n",
      "→ Retrieved 20 tracks for soundtrack\n",
      "\n",
      "🎧 Processing genre: relaxation\n",
      "→ Retrieved 20 tracks for relaxation\n",
      "\n",
      "🎧 Processing genre: world\n",
      "→ Retrieved 20 tracks for world\n",
      "\n",
      "🎧 Processing genre: blues\n",
      "→ Retrieved 20 tracks for blues\n",
      "\n",
      "🎧 Processing genre: funk\n",
      "→ Retrieved 20 tracks for funk\n",
      "\n",
      "🎧 Processing genre: reggae\n",
      "→ Retrieved 20 tracks for reggae\n",
      "\n",
      "🎧 Processing genre: latin\n",
      "→ Retrieved 20 tracks for latin\n",
      "\n",
      "🎧 Processing genre: ambient\n",
      "→ Retrieved 20 tracks for ambient\n",
      "❌ Error uploading track 10 for genre ambient: Timeout of 120.0s exceeded, last exception: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/uchicago-bayesian-bayes-beats/o?uploadType=resumable&upload_id=AAO2VwqkEcdbVyYiNnX9SvHRF4Lsvpc8uBgykKAPUw4NHWN1uh9vyfgtwBopQhMnw4wy13b4683rRyU5ve05auUvf6g-6C687HVwhVGxtK-PaQ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10680d150>: Failed to resolve 'storage.googleapis.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 11 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1540806&format=mp32&from=JvuGRmS%2B00JEuD5QcFDuLA%3D%3D%7C2OB8EUnllZMjoyAjK%2BbF8A%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10688d4b0>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 12 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1280383&format=mp32&from=%2Fh0R5T0WB9%2Fz4rkLvLd47Q%3D%3D%7CLpbHJZTiqkusVI%2F%2FfM4zhA%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10688f0a0>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 13 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=131261&format=mp32&from=DEOgQ%2B0IFVqLZnGx4oEJmA%3D%3D%7CZhI%2BUtZ671Zvia1XRCz48w%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1069043d0>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 14 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=263741&format=mp32&from=SGBug37Z24BcxNhONnHqrA%3D%3D%7C8PJY4eq%2BWOrgGecqb5eVjw%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10688fe80>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 15 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1841795&format=mp32&from=Fcx%2F%2FNtpoBdJf7%2BUPsIRJA%3D%3D%7CHuoq9oN1qqY3LXBA5Xj%2B7w%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10688f040>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 16 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1121816&format=mp32&from=ABy5kzlBCxfU4GSP6wDn%2Bw%3D%3D%7C5lx3hyGU%2BmK82TTWgMfQag%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10680f760>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 17 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1121828&format=mp32&from=x14Ylsi5EdHhc%2FWuv7m7uw%3D%3D%7CRf9dY9FZO%2BfOoRdPFYFWIw%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x106904be0>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 18 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=1540805&format=mp32&from=hO%2BhuWWWF5DJRU9vt6RiUg%3D%3D%7C%2BVBykmkYS5c1JVQCVD9QVQ%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1069053f0>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "❌ Error uploading track 19 for genre ambient: HTTPSConnectionPool(host='prod-1.storage.jamendo.com', port=443): Max retries exceeded with url: /?trackid=979861&format=mp32&from=sp4BgDHmgRVa7jBy%2BdEJxA%3D%3D%7Ca3JgL8FSPlBihI9X7c3sxQ%3D%3D (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x106905c30>: Failed to resolve 'prod-1.storage.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "\n",
      "🎧 Processing genre: folk\n"
     ]
    },
    {
     "ename": "ConnectionError",
     "evalue": "HTTPSConnectionPool(host='api.jamendo.com', port=443): Max retries exceeded with url: /v3.0/tracks?client_id=a62fe3ee&format=json&limit=20&audioformat=mp32&include=musicinfo&tags=folk (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10680f040>: Failed to resolve 'api.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mgaierror\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connection.py:198\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    197\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 198\u001b[0m     sock \u001b[38;5;241m=\u001b[39m \u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcreate_connection\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    199\u001b[0m \u001b[43m        \u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_dns_host\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mport\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    200\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    201\u001b[0m \u001b[43m        \u001b[49m\u001b[43msource_address\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msource_address\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    202\u001b[0m \u001b[43m        \u001b[49m\u001b[43msocket_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msocket_options\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    203\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m socket\u001b[38;5;241m.\u001b[39mgaierror \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/util/connection.py:60\u001b[0m, in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[1;32m     58\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m LocationParseError(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mhost\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m, label empty or too long\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m---> 60\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[43msocket\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgetaddrinfo\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mport\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfamily\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43msocket\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mSOCK_STREAM\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[1;32m     61\u001b[0m     af, socktype, proto, canonname, sa \u001b[38;5;241m=\u001b[39m res\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/lib/python3.10/socket.py:955\u001b[0m, in \u001b[0;36mgetaddrinfo\u001b[0;34m(host, port, family, type, proto, flags)\u001b[0m\n\u001b[1;32m    954\u001b[0m addrlist \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m--> 955\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[43m_socket\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgetaddrinfo\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mport\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfamily\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mtype\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproto\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mflags\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[1;32m    956\u001b[0m     af, socktype, proto, canonname, sa \u001b[38;5;241m=\u001b[39m res\n",
      "\u001b[0;31mgaierror\u001b[0m: [Errno 8] nodename nor servname provided, or not known",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mNameResolutionError\u001b[0m                       Traceback (most recent call last)",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connectionpool.py:787\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[1;32m    786\u001b[0m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[0;32m--> 787\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_make_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    788\u001b[0m \u001b[43m    \u001b[49m\u001b[43mconn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    789\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    790\u001b[0m \u001b[43m    \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    791\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_obj\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    792\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    793\u001b[0m \u001b[43m    \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    794\u001b[0m \u001b[43m    \u001b[49m\u001b[43mchunked\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    795\u001b[0m \u001b[43m    \u001b[49m\u001b[43mretries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mretries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    796\u001b[0m \u001b[43m    \u001b[49m\u001b[43mresponse_conn\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mresponse_conn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    797\u001b[0m \u001b[43m    \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpreload_content\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    798\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdecode_content\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    799\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mresponse_kw\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    800\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    802\u001b[0m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connectionpool.py:488\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[1;32m    487\u001b[0m         new_e \u001b[38;5;241m=\u001b[39m _wrap_proxy_error(new_e, conn\u001b[38;5;241m.\u001b[39mproxy\u001b[38;5;241m.\u001b[39mscheme)\n\u001b[0;32m--> 488\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m new_e\n\u001b[1;32m    490\u001b[0m \u001b[38;5;66;03m# conn.request() calls http.client.*.request, not the method in\u001b[39;00m\n\u001b[1;32m    491\u001b[0m \u001b[38;5;66;03m# urllib3.request. It also calls makefile (recv) on the socket.\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connectionpool.py:464\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[1;32m    463\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 464\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_validate_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconn\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    465\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connectionpool.py:1093\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1092\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m conn\u001b[38;5;241m.\u001b[39mis_closed:\n\u001b[0;32m-> 1093\u001b[0m     \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1095\u001b[0m \u001b[38;5;66;03m# TODO revise this, see https://github.com/urllib3/urllib3/issues/2791\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connection.py:704\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    703\u001b[0m sock: socket\u001b[38;5;241m.\u001b[39msocket \u001b[38;5;241m|\u001b[39m ssl\u001b[38;5;241m.\u001b[39mSSLSocket\n\u001b[0;32m--> 704\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msock \u001b[38;5;241m=\u001b[39m sock \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_new_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    705\u001b[0m server_hostname: \u001b[38;5;28mstr\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhost\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connection.py:205\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m socket\u001b[38;5;241m.\u001b[39mgaierror \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m--> 205\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m NameResolutionError(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhost, \u001b[38;5;28mself\u001b[39m, e) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01me\u001b[39;00m\n\u001b[1;32m    206\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m SocketTimeout \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[0;31mNameResolutionError\u001b[0m: <urllib3.connection.HTTPSConnection object at 0x10680f040>: Failed to resolve 'api.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/adapters.py:667\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    666\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 667\u001b[0m     resp \u001b[38;5;241m=\u001b[39m \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43murlopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    668\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    669\u001b[0m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    670\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    671\u001b[0m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    672\u001b[0m \u001b[43m        \u001b[49m\u001b[43mredirect\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    673\u001b[0m \u001b[43m        \u001b[49m\u001b[43massert_same_host\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    674\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    675\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    676\u001b[0m \u001b[43m        \u001b[49m\u001b[43mretries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    677\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    678\u001b[0m \u001b[43m        \u001b[49m\u001b[43mchunked\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    679\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    681\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (ProtocolError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/connectionpool.py:841\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[1;32m    839\u001b[0m     new_e \u001b[38;5;241m=\u001b[39m ProtocolError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mConnection aborted.\u001b[39m\u001b[38;5;124m\"\u001b[39m, new_e)\n\u001b[0;32m--> 841\u001b[0m retries \u001b[38;5;241m=\u001b[39m \u001b[43mretries\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mincrement\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    842\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mnew_e\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_pool\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_stacktrace\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msys\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexc_info\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m]\u001b[49m\n\u001b[1;32m    843\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    844\u001b[0m retries\u001b[38;5;241m.\u001b[39msleep()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/urllib3/util/retry.py:519\u001b[0m, in \u001b[0;36mRetry.increment\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    518\u001b[0m     reason \u001b[38;5;241m=\u001b[39m error \u001b[38;5;129;01mor\u001b[39;00m ResponseError(cause)\n\u001b[0;32m--> 519\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m MaxRetryError(_pool, url, reason) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mreason\u001b[39;00m  \u001b[38;5;66;03m# type: ignore[arg-type]\u001b[39;00m\n\u001b[1;32m    521\u001b[0m log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIncremented Retry for (url=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m): \u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, url, new_retry)\n",
      "\u001b[0;31mMaxRetryError\u001b[0m: HTTPSConnectionPool(host='api.jamendo.com', port=443): Max retries exceeded with url: /v3.0/tracks?client_id=a62fe3ee&format=json&limit=20&audioformat=mp32&include=musicinfo&tags=folk (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10680f040>: Failed to resolve 'api.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 35\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m🎧 Processing genre: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mgenre\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     27\u001b[0m params \u001b[38;5;241m=\u001b[39m {\n\u001b[1;32m     28\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mclient_id\u001b[39m\u001b[38;5;124m\"\u001b[39m: CLIENT_ID,\n\u001b[1;32m     29\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mformat\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mjson\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     33\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtags\u001b[39m\u001b[38;5;124m\"\u001b[39m: genre\n\u001b[1;32m     34\u001b[0m }\n\u001b[0;32m---> 35\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[43mrequests\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mhttps://api.jamendo.com/v3.0/tracks\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     36\u001b[0m tracks \u001b[38;5;241m=\u001b[39m resp\u001b[38;5;241m.\u001b[39mjson()\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mresults\u001b[39m\u001b[38;5;124m\"\u001b[39m, [])\n\u001b[1;32m     37\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m→ Retrieved \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mlen\u001b[39m(tracks)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m tracks for \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mgenre\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/api.py:73\u001b[0m, in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mget\u001b[39m(url, params\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m     63\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124mr\u001b[39m\u001b[38;5;124;03m\"\"\"Sends a GET request.\u001b[39;00m\n\u001b[1;32m     64\u001b[0m \n\u001b[1;32m     65\u001b[0m \u001b[38;5;124;03m    :param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     70\u001b[0m \u001b[38;5;124;03m    :rtype: requests.Response\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m---> 73\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mrequest\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mget\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/api.py:59\u001b[0m, in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     55\u001b[0m \u001b[38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we\u001b[39;00m\n\u001b[1;32m     56\u001b[0m \u001b[38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some\u001b[39;00m\n\u001b[1;32m     57\u001b[0m \u001b[38;5;66;03m# cases, and look like a memory leak in others.\u001b[39;00m\n\u001b[1;32m     58\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m sessions\u001b[38;5;241m.\u001b[39mSession() \u001b[38;5;28;01mas\u001b[39;00m session:\n\u001b[0;32m---> 59\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43msession\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/sessions.py:589\u001b[0m, in \u001b[0;36mSession.request\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    584\u001b[0m send_kwargs \u001b[38;5;241m=\u001b[39m {\n\u001b[1;32m    585\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtimeout\u001b[39m\u001b[38;5;124m\"\u001b[39m: timeout,\n\u001b[1;32m    586\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mallow_redirects\u001b[39m\u001b[38;5;124m\"\u001b[39m: allow_redirects,\n\u001b[1;32m    587\u001b[0m }\n\u001b[1;32m    588\u001b[0m send_kwargs\u001b[38;5;241m.\u001b[39mupdate(settings)\n\u001b[0;32m--> 589\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprep\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43msend_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    591\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/sessions.py:703\u001b[0m, in \u001b[0;36mSession.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    700\u001b[0m start \u001b[38;5;241m=\u001b[39m preferred_clock()\n\u001b[1;32m    702\u001b[0m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m r \u001b[38;5;241m=\u001b[39m \u001b[43madapter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    705\u001b[0m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[1;32m    706\u001b[0m elapsed \u001b[38;5;241m=\u001b[39m preferred_clock() \u001b[38;5;241m-\u001b[39m start\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.13/envs/bayes-final/lib/python3.10/site-packages/requests/adapters.py:700\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    696\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(e\u001b[38;5;241m.\u001b[39mreason, _SSLError):\n\u001b[1;32m    697\u001b[0m         \u001b[38;5;66;03m# This branch is for urllib3 v1.22 and later.\u001b[39;00m\n\u001b[1;32m    698\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m SSLError(e, request\u001b[38;5;241m=\u001b[39mrequest)\n\u001b[0;32m--> 700\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(e, request\u001b[38;5;241m=\u001b[39mrequest)\n\u001b[1;32m    702\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ClosedPoolError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    703\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(e, request\u001b[38;5;241m=\u001b[39mrequest)\n",
      "\u001b[0;31mConnectionError\u001b[0m: HTTPSConnectionPool(host='api.jamendo.com', port=443): Max retries exceeded with url: /v3.0/tracks?client_id=a62fe3ee&format=json&limit=20&audioformat=mp32&include=musicinfo&tags=folk (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10680f040>: Failed to resolve 'api.jamendo.com' ([Errno 8] nodename nor servname provided, or not known)\"))"
     ]
    }
   ],
   "source": [
    "import requests, json, io\n",
    "from google.cloud import storage\n",
    "from tqdm import tqdm\n",
    "\n",
    "# --- Config ---\n",
    "BUCKET_NAME = \"uchicago-bayesian-bayes-beats\"\n",
    "BASE_FOLDER = \"jamendo_by_genre\"\n",
    "CLIENT_ID = \"a62fe3ee\"\n",
    "AUDIO_FORMAT = \"mp32\"\n",
    "TRACKS_PER_GENRE = 20\n",
    "\n",
    "\n",
    "\n",
    "# --- Initialize GCS ---\n",
    "client = storage.Client()\n",
    "bucket = client.bucket(BUCKET_NAME)\n",
    "\n",
    "# \"rock\", \"pop\",\n",
    "GENRES = [\n",
    "     \"electronic\", \"jazz\", \"hiphop\",\n",
    "    \"classical\", \"metal\", \"soundtrack\", \"relaxation\", \"world\",\n",
    "    \"blues\", \"funk\", \"reggae\", \"latin\", \"ambient\",\n",
    "    \"folk\", \"techno\", \"punk\", \"house\", \"experimental\"\n",
    "]\n",
    "\n",
    "# --- Loop by Genre ---\n",
    "for genre in GENRES:\n",
    "    print(f\"\\n🎧 Processing genre: {genre}\")\n",
    "    params = {\n",
    "        \"client_id\": CLIENT_ID,\n",
    "        \"format\": \"json\",\n",
    "        \"limit\": TRACKS_PER_GENRE,\n",
    "        \"audioformat\": AUDIO_FORMAT,\n",
    "        \"include\": \"musicinfo\",\n",
    "        \"tags\": genre\n",
    "    }\n",
    "    resp = requests.get(\"https://api.jamendo.com/v3.0/tracks\", params=params)\n",
    "    tracks = resp.json().get(\"results\", [])\n",
    "    print(f\"→ Retrieved {len(tracks)} tracks for {genre}\")\n",
    "\n",
    "    for i, track in enumerate(tracks):\n",
    "        try:\n",
    "            title = track[\"name\"].replace(\" \", \"_\")\n",
    "            artist = track[\"artist_name\"].replace(\" \", \"_\")\n",
    "            filename = f\"{i:02d}_{artist}_{title}.mp3\"\n",
    "\n",
    "            # Download MP3\n",
    "            audio_resp = requests.get(track[\"audio\"])\n",
    "            audio_resp.raise_for_status()\n",
    "            buffer = io.BytesIO(audio_resp.content)\n",
    "            buffer.seek(0)\n",
    "\n",
    "            # Upload MP3\n",
    "            audio_blob = bucket.blob(f\"{BASE_FOLDER}/{genre}/{filename}\")\n",
    "            audio_blob.upload_from_file(buffer, content_type=\"audio/mpeg\")\n",
    "\n",
    "            # Upload metadata JSON\n",
    "            metadata = {\n",
    "                \"id\": track[\"id\"],\n",
    "                \"name\": track[\"name\"],\n",
    "                \"artist\": track[\"artist_name\"],\n",
    "                \"album\": track.get(\"album_name\"),\n",
    "                \"duration\": track[\"duration\"],\n",
    "                \"tags\": track.get(\"musicinfo\", {}).get(\"tags\", []),\n",
    "                \"genres\": track.get(\"musicinfo\", {}).get(\"genres\", []),\n",
    "                \"instruments\": track.get(\"musicinfo\", {}).get(\"instruments\", []),\n",
    "                \"vocalinstrumental\": track.get(\"musicinfo\", {}).get(\"vocalinstrumental\")\n",
    "            }\n",
    "            meta_blob = bucket.blob(f\"{BASE_FOLDER}/{genre}/{filename.replace('.mp3','.json')}\")\n",
    "            meta_blob.upload_from_string(json.dumps(metadata), content_type=\"application/json\")\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"❌ Error uploading track {i} for genre {genre}: {e}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "bayes-final",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
